### ISSUE TITLE
PostService 수정 이슈

### ISSUE THREAD

**Issue by destiny3912** [Debri-Development-Team/Server#169]
1.  PostService 유저 존재 여부 validation 삭제
  - 무조건 User 체크한다고 다 삭제는 아닐거에요 로직 흐름에 필요 없는거만 삭제 부탁 드릴게요
2.  130Line, 162Line에 있는 scrapPost, unscrapPost 메서드  try-catch 적용
3. 162Line unScrapPost 메서드에서 if(postProvider.checkPostMarkedExist(postIdx, userIdx) == 0) 에서 오류 코드를 던지는 것으로 수정
4. 70Line에 deletePost 메서드 validation 위치 조정 -> try 밖으로
5. 145Line ScrapPost 메서드에 스크랩 여부 관련 validation 추가 
   - 예를 들어서 이미 스크랩을 한 게시물에 다시 스크랩 요청을 한다던가 하는 경유

**Comment by KangGeonyoung** [comment]
Issue/169-5 관련 의견
- 코드를 확인해보면 받은 postIdx가 PostMarked(스크랩 테이블) 테이블 안에 있는 지에 따라서 validation 처리가 되어 있습니다.
- 스크랩 한 게시물에 다시 스크랩을 하면 스크랩이 취소되는 것으로 알고 있습니다. 
굳이 스크랩 된 게시물의 활성화된 스크랩 버튼을 다시 눌렀을 때 "이미 스크랩된 게시물입니다." 라는 문구를 띄울 필요가
없을 것 같습니다. 
예시로 에브리타임을 보면 게시물에 들어가 스크랩을 누르면 스크랩 취소 버튼으로 바뀌고 스크랩 취소 버튼을 누르면 바로 스크랩 취소가 됩니다.
- Issue/169-5의 경우는 안드로이드 측에서 스크랩 버튼 색상에 따라서 API를 호출하는 것이기 때문에 서버 측에서 신경 쓰지 않아도 될 것 같습니다.
